Repository DataDog/watermarkpodautoscaler, pull requests merged in 2020-08, with the labels that each got.

#57 add labels_info metric to support additional labels as tags
  deploy/operator.yaml
  pkg/controller/watermarkpodautoscaler/metrics.go
  pkg/controller/watermarkpodautoscaler/watermarkpodautoscaler_controller.go
Labels: enhancement

#61 Fix metrics cleanup
  pkg/controller/watermarkpodautoscaler/metrics.go
  pkg/controller/watermarkpodautoscaler/replica_calculator.go
  pkg/controller/watermarkpodautoscaler/watermarkpodautoscaler_controller.go
Labels: bug

#62 Fix WPA Resource type RBAC
  chart/watermarkpodautoscaler/templates/clusterrole.yaml
  deploy/clusterrole.yaml
Labels: bug

#63 Add example CRs
  examples/external-type.yaml
  examples/resource-type.yaml
Labels: documentation

#64 Add DCA helm chart instruction
  README.md
Labels: documentation
