Repository DataDog/watermarkpodautoscaler, pull requests merged in 2024-06, with the labels that each got.

#210 metrics: add count for number of upscale and downscale
  controllers/metrics.go
  controllers/watermarkpodautoscaler_controller.go
Labels: enhancement

#211 fix(ci): use new goreleaser parameter
  .github/workflows/build.yaml
  .github/workflows/release.yaml
Labels: bug, tooling, mergequeue-status: rejected

#214 add merge queue config
  repository.datadog.yml
Labels: tooling, qa/skip-qa

#212 fix(ci): migrate to registry.ddbuild.io for ci images
  .gitlab-ci.yml
  Makefile
Labels: bug, tooling

#164 Add the possibility to configure the api-server client timeout
  main.go
Labels: enhancement

#195 Add Prometheus metrics verification to reconciler test
  controllers/watermarkpodautoscaler_controller_test.go
Labels: enhancement, qa/skip-qa, mergequeue-status: in_progress

#209 Fix yq command in patch-chart.sh
  Makefile
  hack/patch-chart.sh
Labels: tooling, qa/skip-qa, mergequeue-status: rejected
