Repository DataDog/watermarkpodautoscaler, pull requests merged in 2024-10, with the labels that each got.

#221 [CONTINT-4412] Upgrade `k8s` dependencies
  .devcontainer/devcontainer.json
  .github/workflows/build.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/release.yaml
  .github/workflows/validation.yaml
  .gitlab-ci.yml
  .golangci.toml
  Dockerfile
  LICENSE-3rdparty.csv
  Makefile
  apis/datadoghq/v1alpha1/watermarkpodautoscaler_default.go
  apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  apis/datadoghq/v1alpha1/zz_generated.openapi.go
  bundle/manifests/datadoghq.com_watermarkpodautoscalers.yaml
  bundle/manifests/watermarkpodautoscaler.clusterserviceversion.yaml
  chart/watermarkpodautoscaler/CHANGELOG.md
  chart/watermarkpodautoscaler/templates/datadoghq.com_watermarkpodautoscalers_crd_v1.yaml
  cmd/kubectl-wpa/app/common/client.go
  config/crd/bases/v1/datadoghq.com_watermarkpodautoscalers.yaml
  config/crd/bases/v1beta1/datadoghq.com_watermarkpodautoscalers.yaml
  config/manager/kustomization.yaml
  config/rbac/role.yaml
  controllers/datadoghq/replica_calculator.go
  controllers/datadoghq/replica_calculator_test.go
  controllers/datadoghq/test/suite_test.go
  controllers/datadoghq/watermarkpodautoscaler_controller.go
  controllers/datadoghq/watermarkpodautoscaler_controller_test.go
  go.mod
  go.sum
  main.go
  pkg/config/config.go
Labels: dependencies, mergequeue-status: in_progress

#223 recommender: Initial support for third-party replica recommenders
  apis/datadoghq/v1alpha1/watermarkpodautoscaler_default.go
  apis/datadoghq/v1alpha1/watermarkpodautoscaler_types.go
  apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1/datadoghq.com_watermarkpodautoscalers.yaml
  config/crd/bases/v1beta1/datadoghq.com_watermarkpodautoscalers.yaml
  config/manager/kustomization.yaml
  config/samples/recommender.yaml
  controllers/datadoghq/recommender.go
  controllers/datadoghq/recommender_test.go
  controllers/datadoghq/replica_calculator.go
  controllers/datadoghq/replica_calculator_test.go
  controllers/datadoghq/watermarkpodautoscaler_controller.go
  controllers/datadoghq/watermarkpodautoscaler_controller_test.go
  pkg/math32/math32.go
Labels: enhancement, mergequeue-status: in_progress

#225 recommender: initial support of HTTP+JSON recommenders
  LICENSE-3rdparty.csv
  apis/datadoghq/v1alpha1/watermarkpodautoscaler_types.go
  cmd/skeleton-recommender/main.go
  config/crd/bases/v1/datadoghq.com_watermarkpodautoscalers.yaml
  config/crd/bases/v1beta1/datadoghq.com_watermarkpodautoscalers.yaml
  config/manager/kustomization.yaml
  config/samples/recommender.yaml
  controllers/datadoghq/recommender.go
  controllers/datadoghq/recommender_test.go
  controllers/datadoghq/replica_calculator.go
  go.mod
  go.sum
Labels: enhancement

#226 Fix the generation of OpenAPI
  Makefile
  apis/datadoghq/v1alpha1/zz_generated.openapi.go
Labels: bug, mergequeue-status: rejected
