Repository DataDog/watermarkpodautoscaler, pull requests merged in 2024-12, with the labels that each got.

#241 add pr backport script
  .github/workflows/pr-backport.yaml
Labels: tooling, mergequeue-status: in_progress

#242 [controllers/wpa] Remove dependency from datadog-operator by using Unstructured
  LICENSE-3rdparty.csv
  controllers/datadoghq/watermarkpodautoscaler_controller.go
  controllers/datadoghq/watermarkpodautoscaler_controller_test.go
  go.mod
  go.sum
  main.go
Labels: enhancement, mergequeue-status: in_progress

#243 recommenders: attach the current cluster name
  controllers/datadoghq/recommender.go
  controllers/datadoghq/replica_calculator.go
  controllers/datadoghq/replica_calculator_test.go
  controllers/datadoghq/watermarkpodautoscaler_controller.go
Labels: bug, mergequeue-status: in_progress

#247 Update internal image template version to v3
  .gitlab-ci.yml
Labels: tooling, mergequeue-status: in_progress

#246 Update zap
  go.mod
  go.sum
Labels: dependencies, mergequeue-status: in_progress
