Repository DataDog/watermarkpodautoscaler, pull requests merged in 2024-11, with the labels that each got.

#228 Fix operator deps not existing + panic on nil map + panic not printed to stdout
  .github/workflows/build.yaml
  .github/workflows/release.yaml
  apis/datadoghq/v1alpha1/zz_generated.openapi.go
  go.mod
  go.sum
  main.go
  pkg/config/config.go
Labels: bug, dependencies

#227 recommender: add metrics for recommender http actions
  LICENSE-3rdparty.csv
  cmd/skeleton-recommender/main.go
  controllers/datadoghq/metrics.go
  controllers/datadoghq/recommender.go
  controllers/datadoghq/recommender_test.go
  controllers/datadoghq/watermarkpodautoscaler_controller.go
  go.mod
  go.sum
Labels: enhancement, mergequeue-status: in_progress

#230 recommender: fix instrumentation and add tests
  controllers/datadoghq/metrics.go
  controllers/datadoghq/recommender.go
  controllers/datadoghq/recommender_test.go
Labels: bug

#231 Configure Github workflow and job level permissions
  .github/workflows/build.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/pr-linter.yaml
  .github/workflows/release.yaml
  .github/workflows/validation.yaml
Labels: tooling, qa/skip-qa

#232 Add watermarkpodautoscaler service file
  service.datadog.yaml
Labels: tooling, qa/skip-qa

#233 Setup nightly build
  service.datadog.yaml
Labels: tooling, qa/skip-qa

#235 fix: remove temporary gitlab cache to fix ci build
  .gitlab-ci.yml
Labels: tooling, mergequeue-status: in_progress

#236 fix: github token in github actions
  .github/workflows/pr-linter.yaml
  .github/workflows/release.yaml
Labels: tooling, mergequeue-status: in_progress, github_actions

#238 fix app-id in github actions
  .github/workflows/pr-linter.yaml
  .github/workflows/release.yaml
Labels: bug, tooling, mergequeue-status: in_progress, github_actions

#239 fallback to static token for now
  .github/workflows/pr-linter.yaml
  .github/workflows/release.yaml
Labels: tooling, mergequeue-status: in_progress

#237 reintroduce gitlabci cache
  .gitlab-ci.yml
Labels: tooling, mergequeue-status: in_progress
