Repository DataDog/watermarkpodautoscaler, pull requests merged in 2025-01, with the labels that each got.

#253 fix: kubectl-wpa plugin releasing
  hack/release/generate-plugin-manifest.sh
Labels: bug, mergequeue-status: in_progress

#256 Fix recommender API low/high watermark handling when < 1
  controllers/datadoghq/recommender.go
  controllers/datadoghq/recommender_test.go
Labels: bug, mergequeue-status: in_progress, backport/v0.9

#250 Create go module for the CRD
  Dockerfile
  LICENSE-3rdparty.csv
  apis/go.mod
  apis/go.sum
  go.work
  go.work.sum
  hack/update-golang.sh
Labels: enhancement, mergequeue-status: in_progress

#258 recommender: make sure the metric name is stable
  controllers/datadoghq/recommender.go
  controllers/datadoghq/recommender_test.go
Labels: bug, mergequeue-status: in_progress

#255 Update kubectl-plugin.md
  docs/kubectl-plugin.md
Labels: documentation

#259 recommender: propagate the observed value to the status
  controllers/datadoghq/recommender.go
  controllers/datadoghq/recommender_test.go
  controllers/datadoghq/replica_calculator.go
  controllers/datadoghq/watermarkpodautoscaler_controller.go
Labels: enhancement, mergequeue-status: in_progress

#265 Display low/high watermarks for both external metrics & recommender
  apis/datadoghq/v1alpha1/watermarkpodautoscaler_types.go
  config/crd/bases/v1/datadoghq.com_watermarkpodautoscalers.yaml
  config/crd/bases/v1beta1/datadoghq.com_watermarkpodautoscalers.yaml
Labels: enhancement

#268 Bump WPA chart version to v0.5.0
  chart/watermarkpodautoscaler/Chart.yaml
Labels: enhancement

#267 Update example chart with new CRD definitions
  chart/watermarkpodautoscaler/CHANGELOG.md
  chart/watermarkpodautoscaler/Chart.yaml
  chart/watermarkpodautoscaler/templates/datadoghq.com_watermarkpodautoscalers_crd_v1.yaml
  chart/watermarkpodautoscaler/templates/datadoghq.com_watermarkpodautoscalers_crd_v1beta1.yaml
Labels: enhancement

#264 Use recommender reason to decorate reconciler status
  controllers/datadoghq/replica_calculator.go
  controllers/datadoghq/replica_calculator_test.go
  controllers/datadoghq/watermarkpodautoscaler_controller.go
  controllers/datadoghq/watermarkpodautoscaler_controller_test.go
Labels: enhancement, mergequeue-status: in_progress

#266 recommender: adjust metric display
  controllers/datadoghq/replica_calculator.go
  controllers/datadoghq/watermarkpodautoscaler_controller.go
Labels: bug, mergequeue-status: in_progress

#269 Fix lower/upper bound inversion in recommender replica calculation
  controllers/datadoghq/replica_calculator.go
  controllers/datadoghq/replica_calculator_test.go
Labels: bug, mergequeue-status: in_progress

#270 Fix release github worflow
  .github/workflows/release.yaml
Labels: bug, no_qa, tooling, mergequeue-status: in_progress, backport/v0.9
