Repository DataDog/watermarkpodautoscaler, pull requests merged in 2025-04, with the labels that each got.

#286 Handle metric computations errors and don't reset conditions
  controllers/datadoghq/watermarkpodautoscaler_controller.go
Labels: bug

#290 Generate fips image compiled with Go boringcrypto
  .gitlab-ci.yml
  Dockerfile
  Makefile
  pkg/util/fipsonly.go
Labels: tooling, backport/v0.10

#292 Remove global gitlab cache
  .gitlab-ci.yml
Labels: tooling

#289 Clarify how 'tolerance' is used in computing the desired replicas
  README.md
Labels: documentation, mergequeue-status: in_progress

#287 doc(README): Update docs to explain why you shouldn't set replicas in the deployment
  README.md
Labels: documentation, qa/skip-qa, mergequeue-status: in_progress

#251 Provide gauge metrics for some recommender conditions
  controllers/datadoghq/metrics.go
  controllers/datadoghq/watermarkpodautoscaler_controller.go
  controllers/datadoghq/watermarkpodautoscaler_controller_test.go
Labels: enhancement, mergequeue-status: in_progress

#293 Fix the metric_name: label when using a recommender
  controllers/datadoghq/replica_calculator.go
Labels: bug
