Repository DataDog/watermarkpodautoscaler, pull requests merged in 2025-03, with the labels that each got.

#273 Add Datadog tracing
  LICENSE-3rdparty.csv
  apis/go.mod
  apis/go.sum
  controllers/datadoghq/recommender.go
  controllers/datadoghq/recommender_test.go
  controllers/datadoghq/replica_calculator.go
  controllers/datadoghq/replica_calculator_test.go
  controllers/datadoghq/watermarkpodautoscaler_controller.go
  controllers/datadoghq/watermarkpodautoscaler_controller_test.go
  go.mod
  go.sum
  go.work.sum
  main.go
  pkg/util/trace.go
Labels: enhancement

#279 Fix two panics
  controllers/datadoghq/replica_calculator.go
  controllers/datadoghq/watermarkpodautoscaler_controller.go
Labels: bug

#278 Fix Evicted Pods Skewing Available Replicas Calculation
  controllers/datadoghq/replica_calculator.go
  controllers/datadoghq/replica_calculator_test.go
Labels: bug, qa/skip-qa, mergequeue-status: in_progress

#281 Add Gitlab job for building FIPS enabled image for GovCloud
  .gitlab-ci.yml
Labels: tooling, backport/v0.10

#272 Fix public image releasing
  .gitlab-ci.yml
Labels: bug, tooling, mergequeue-status: in_progress, backport/v0.10

#277 fix: Fix problematic error returns
  test/e2e/metricsserver/metricsserver.go
Labels: bug, qa/skip-qa, mergequeue-status: in_progress

#280 fix(releasing): use github token for getting the last release tag
  .github/workflows/release.yaml
Labels: bug, tooling, mergequeue-status: in_progress, backport/v0.10

#285 Add more metrics to detect broken WPAs
  controllers/datadoghq/metrics.go
  controllers/datadoghq/recommender.go
  controllers/datadoghq/watermarkpodautoscaler_controller.go
  controllers/datadoghq/watermarkpodautoscaler_controller_test.go
Labels: enhancement, mergequeue-status: in_progress
